# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/Forms/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 385)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menubar.setObjectName("menubar")
        self.tables = QtWidgets.QMenu(self.menubar)
        self.tables.setObjectName("tables")
        self.analys = QtWidgets.QMenu(self.menubar)
        self.analys.setObjectName("analys")
        self.fin = QtWidgets.QMenu(self.menubar)
        self.fin.setObjectName("fin")
        self.progactions = QtWidgets.QMenu(self.menubar)
        self.progactions.setObjectName("progactions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.nir = QtWidgets.QAction(MainWindow)
        self.nir.setObjectName("nir")
        self.prog = QtWidgets.QAction(MainWindow)
        self.prog.setObjectName("prog")
        self.vuz = QtWidgets.QAction(MainWindow)
        self.vuz.setObjectName("vuz")
        self.closeaction = QtWidgets.QAction(MainWindow)
        self.closeaction.setObjectName("closeaction")
        self.analys1 = QtWidgets.QAction(MainWindow)
        self.analys1.setObjectName("analys1")
        self.analys2 = QtWidgets.QAction(MainWindow)
        self.analys2.setObjectName("analys2")
        self.analys3 = QtWidgets.QAction(MainWindow)
        self.analys3.setObjectName("analys3")
        self.orderbtn = QtWidgets.QAction(MainWindow)
        self.orderbtn.setObjectName("orderbtn")
        self.aboutbtn = QtWidgets.QAction(MainWindow)
        self.aboutbtn.setObjectName("aboutbtn")
        self.helpbtn = QtWidgets.QAction(MainWindow)
        self.helpbtn.setObjectName("helpbtn")
        self.closebtn = QtWidgets.QAction(MainWindow)
        self.closebtn.setObjectName("closebtn")
        self.tables.addAction(self.nir)
        self.tables.addAction(self.prog)
        self.tables.addAction(self.vuz)
        self.analys.addAction(self.analys1)
        self.analys.addAction(self.analys2)
        self.analys.addAction(self.analys3)
        self.fin.addAction(self.orderbtn)
        self.progactions.addAction(self.aboutbtn)
        self.progactions.addAction(self.helpbtn)
        self.progactions.addAction(self.closebtn)
        self.menubar.addAction(self.tables.menuAction())
        self.menubar.addAction(self.analys.menuAction())
        self.menubar.addAction(self.fin.menuAction())
        self.menubar.addAction(self.progactions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сопровождение НТП"))
        self.tables.setTitle(_translate("MainWindow", " Данные"))
        self.analys.setTitle(_translate("MainWindow", "Анализ данных"))
        self.fin.setTitle(_translate("MainWindow", "Финансирование"))
        self.progactions.setTitle(_translate("MainWindow", "Программа"))
        self.nir.setText(_translate("MainWindow", "Таблица с НИР"))
        self.prog.setText(_translate("MainWindow", "Таблица с НТП"))
        self.vuz.setText(_translate("MainWindow", "Данные о вузах"))
        self.closeaction.setText(_translate("MainWindow", "Закрыть"))
        self.analys1.setText(_translate("MainWindow", "Распределение НИР по вузам"))
        self.analys2.setText(_translate("MainWindow", "Распределение по НТП"))
        self.analys3.setText(_translate("MainWindow", "Характер НИР"))
        self.orderbtn.setText(_translate("MainWindow", "Выдать распоряжение"))
        self.aboutbtn.setText(_translate("MainWindow", "О программе"))
        self.helpbtn.setText(_translate("MainWindow", "Справка"))
        self.closebtn.setText(_translate("MainWindow", "Закрыть"))
