# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forms/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 385)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menubar.setObjectName("menubar")
        self.tables = QtWidgets.QMenu(self.menubar)
        self.tables.setObjectName("tables")
        self.analis = QtWidgets.QMenu(self.menubar)
        self.analis.setObjectName("analis")
        self.fin = QtWidgets.QMenu(self.menubar)
        self.fin.setObjectName("fin")
        self.help = QtWidgets.QMenu(self.menubar)
        self.help.setObjectName("help")
        self.about = QtWidgets.QMenu(self.menubar)
        self.about.setObjectName("about")
        self.closebtn = QtWidgets.QMenu(self.menubar)
        self.closebtn.setObjectName("closebtn")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.nir = QtWidgets.QAction(MainWindow)
        self.nir.setObjectName("nir")
        self.prog = QtWidgets.QAction(MainWindow)
        self.prog.setObjectName("prog")
        self.vuz = QtWidgets.QAction(MainWindow)
        self.vuz.setObjectName("vuz")
        self.closeaction = QtWidgets.QAction(MainWindow)
        self.closeaction.setObjectName("closeaction")
        self.tables.addAction(self.nir)
        self.tables.addAction(self.prog)
        self.tables.addAction(self.vuz)
        self.closebtn.addAction(self.closeaction)
        self.menubar.addAction(self.tables.menuAction())
        self.menubar.addAction(self.analis.menuAction())
        self.menubar.addAction(self.fin.menuAction())
        self.menubar.addAction(self.help.menuAction())
        self.menubar.addAction(self.about.menuAction())
        self.menubar.addAction(self.closebtn.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сопровождение НТП"))
        self.tables.setTitle(_translate("MainWindow", " Данные"))
        self.analis.setTitle(_translate("MainWindow", "Анализ данных"))
        self.fin.setTitle(_translate("MainWindow", "Финансирование"))
        self.help.setTitle(_translate("MainWindow", "Справка"))
        self.about.setTitle(_translate("MainWindow", "О программе"))
        self.closebtn.setTitle(_translate("MainWindow", "Закрыть"))
        self.nir.setText(_translate("MainWindow", "Таблица с НИР"))
        self.prog.setText(_translate("MainWindow", "Таблица с НТП"))
        self.vuz.setText(_translate("MainWindow", "Данные о вузах"))
        self.closeaction.setText(_translate("MainWindow", "Закрыть"))
